#spring:
#  rabbitmq:
#    host: 47.98.41.195
#    port: 5672
#    username: admin
#    password: admin
#    virtualHost: /
#    #消息确认配置项
#    #确认消息已发送到队列(Queue)
#    publisher-returns: true
#    #确认消息已发送到交换机(Exchange)   三种:  1.NONE:默认：禁用发布模式 2.CORRELATED：发布消息成功到交换器后会触发回调方法 3.simple
#    publisher-confirm-type: correlated
